//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Assets/Scripts/Metroid Prime Player/InputSystem/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/Metroid Prime Player/InputSystem/PlayerInputActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Samus Player"",
            ""id"": ""2dbe1e3c-5459-43e8-a3fc-d9c7cb5bb45e"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""5c85e042-8687-4c14-af42-992d63a7621d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""bc6fdd20-e010-483a-951d-ae740f1ceb54"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""27bbd220-506b-4ea9-b158-71df235730c3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""7e4c1851-031b-467f-a036-5dcf2b3a71e7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LockOn"",
                    ""type"": ""Button"",
                    ""id"": ""6fe0804d-a50a-47cd-87cc-c5c8afd2a291"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeaponUp"",
                    ""type"": ""Button"",
                    ""id"": ""555a61e2-8fb3-4336-b94c-10f377ec70c4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeaponRight"",
                    ""type"": ""Button"",
                    ""id"": ""6684ad30-4ccc-4d00-9511-575b5d6c6828"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeaponDown"",
                    ""type"": ""Button"",
                    ""id"": ""c1edc373-3589-4026-803d-5925a126d8e4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeaponLeft"",
                    ""type"": ""Button"",
                    ""id"": ""34656f1a-88c0-4245-9914-29af1bc23b19"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Missiles"",
                    ""type"": ""Button"",
                    ""id"": ""7689ea99-ae1a-4fd1-ab4c-092f4e39197d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Morphball"",
                    ""type"": ""Button"",
                    ""id"": ""615a6990-7738-416b-856d-19f437fc9aaa"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""f03cc56d-439a-4745-8875-6cc2720a8b10"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c035638d-f92c-4620-b98d-8f4e593dcfa8"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""72dc23db-10a2-4eed-8f3d-9056d31af969"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f03b0a1f-089f-4471-b00b-ce02bc10e10e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0bfc7b8b-52fa-46bf-901d-887009c76927"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""03005a2a-db72-4dcf-8496-6b47406fc018"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""93c5010a-c0e9-481a-a266-da4964d9e007"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5e45696-2c29-4d4d-a11f-caea327d6bc9"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""63714111-2971-4416-9f33-3f091dbc3977"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6608fa3c-3b8b-4066-a930-8d29b33afd63"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4d75454-2df9-4e2b-8ec1-4b13d2dde476"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""713916d5-dec3-4994-a786-af58046029cc"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5f02cf7a-6062-4247-9fc1-f79ce3289579"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LockOn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7fcd9658-855b-41e2-9e5d-302a1a8ce907"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LockOn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99c2590d-2fef-41a4-b634-78ffe42c3f71"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb0e5689-1bf1-42df-8404-1ff747eda249"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f040f7a4-a02e-4390-a27f-761e6e2c3051"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""68aac739-d3fe-4f51-ba50-f2d840d05cb1"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0595bb1c-2857-49eb-a8fc-0f5d06b2c831"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5776124d-0be4-4034-949c-a9829a599de5"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3e7ef90-6642-43f9-8930-39a98239b435"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a494dae-eee4-4d50-b397-d88ebef2f25c"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ff30adc-61c4-4fbf-a73a-fa5a533ce602"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Missiles"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2cd36d09-96ad-4b09-b292-4ae41c076e11"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Missiles"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""98092a22-bc47-4f9d-abbe-a7e28cc95b61"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Morphball"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3133f5d-7f32-4a75-ba19-4c9ac12c2d51"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Morphball"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MorphBall"",
            ""id"": ""38408fa4-93fd-4d82-a12d-2c16532941bb"",
            ""actions"": [
                {
                    ""name"": ""MorphBall Move"",
                    ""type"": ""Button"",
                    ""id"": ""8a932e94-089c-4840-9543-30024dc15a41"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Bomb"",
                    ""type"": ""Button"",
                    ""id"": ""bc6ccf77-c228-4aa2-a9e8-b134f160bc0d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Power Bomb"",
                    ""type"": ""Button"",
                    ""id"": ""2b54e9be-b0bc-446a-9116-a9998881a3a7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpiderBall"",
                    ""type"": ""Button"",
                    ""id"": ""755fd206-3703-4318-b10a-5578552952cc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpringBall"",
                    ""type"": ""Button"",
                    ""id"": ""9a513f06-afcc-4e8d-b00c-795698b5caf1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Change Samus"",
                    ""type"": ""Button"",
                    ""id"": ""f1e0a5ba-1749-4313-816e-e695bfc9ccb5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""e971543b-b412-4cc8-a6a7-03265a9a3134"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MorphBall Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f04bab96-4c0f-4d7e-9e6c-844b4cd445b9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MorphBall Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b25f07a6-e2c2-49f4-841a-317c79b6a8b4"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MorphBall Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""297956f7-39a7-409a-a6dd-0718e6a3510f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MorphBall Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7c7316c4-5945-47e6-b4c4-e28ca4e838d8"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MorphBall Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3f44e460-a177-41fb-a291-339a1c034f3f"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MorphBall Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c79704d2-0906-46c5-bcb4-1a3f1140d135"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bomb"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a7282e5-9e51-4962-aaa0-cd922ad183a1"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bomb"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e4a3828b-59d8-400f-aeb3-4a8cf926f2d7"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Power Bomb"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b50ef760-7e2e-4256-8093-b1bec8e46f1d"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Power Bomb"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""01e8d88a-34be-49a8-9b97-cd01abce33fb"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpiderBall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9604fa68-1a7b-4b3f-9dd8-234879c3fd89"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpiderBall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""754a0b8e-3111-4c2e-9c48-0c89b35c16fc"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpringBall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f712aae-c105-411e-b1d7-aadae6d2dcfd"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpringBall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a0b95b4-0ba6-421d-a2f6-f4d1f0b5b5d2"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change Samus"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3566ff72-3539-4b1b-938f-50f36a2ae840"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change Samus"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Samus Player
        m_SamusPlayer = asset.FindActionMap("Samus Player", throwIfNotFound: true);
        m_SamusPlayer_Move = m_SamusPlayer.FindAction("Move", throwIfNotFound: true);
        m_SamusPlayer_Look = m_SamusPlayer.FindAction("Look", throwIfNotFound: true);
        m_SamusPlayer_Jump = m_SamusPlayer.FindAction("Jump", throwIfNotFound: true);
        m_SamusPlayer_Shoot = m_SamusPlayer.FindAction("Shoot", throwIfNotFound: true);
        m_SamusPlayer_LockOn = m_SamusPlayer.FindAction("LockOn", throwIfNotFound: true);
        m_SamusPlayer_WeaponUp = m_SamusPlayer.FindAction("WeaponUp", throwIfNotFound: true);
        m_SamusPlayer_WeaponRight = m_SamusPlayer.FindAction("WeaponRight", throwIfNotFound: true);
        m_SamusPlayer_WeaponDown = m_SamusPlayer.FindAction("WeaponDown", throwIfNotFound: true);
        m_SamusPlayer_WeaponLeft = m_SamusPlayer.FindAction("WeaponLeft", throwIfNotFound: true);
        m_SamusPlayer_Missiles = m_SamusPlayer.FindAction("Missiles", throwIfNotFound: true);
        m_SamusPlayer_Morphball = m_SamusPlayer.FindAction("Morphball", throwIfNotFound: true);
        // MorphBall
        m_MorphBall = asset.FindActionMap("MorphBall", throwIfNotFound: true);
        m_MorphBall_MorphBallMove = m_MorphBall.FindAction("MorphBall Move", throwIfNotFound: true);
        m_MorphBall_Bomb = m_MorphBall.FindAction("Bomb", throwIfNotFound: true);
        m_MorphBall_PowerBomb = m_MorphBall.FindAction("Power Bomb", throwIfNotFound: true);
        m_MorphBall_SpiderBall = m_MorphBall.FindAction("SpiderBall", throwIfNotFound: true);
        m_MorphBall_SpringBall = m_MorphBall.FindAction("SpringBall", throwIfNotFound: true);
        m_MorphBall_ChangeSamus = m_MorphBall.FindAction("Change Samus", throwIfNotFound: true);
    }

    ~@PlayerInputActions()
    {
        UnityEngine.Debug.Assert(!m_SamusPlayer.enabled, "This will cause a leak and performance issues, PlayerInputActions.SamusPlayer.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_MorphBall.enabled, "This will cause a leak and performance issues, PlayerInputActions.MorphBall.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Samus Player
    private readonly InputActionMap m_SamusPlayer;
    private List<ISamusPlayerActions> m_SamusPlayerActionsCallbackInterfaces = new List<ISamusPlayerActions>();
    private readonly InputAction m_SamusPlayer_Move;
    private readonly InputAction m_SamusPlayer_Look;
    private readonly InputAction m_SamusPlayer_Jump;
    private readonly InputAction m_SamusPlayer_Shoot;
    private readonly InputAction m_SamusPlayer_LockOn;
    private readonly InputAction m_SamusPlayer_WeaponUp;
    private readonly InputAction m_SamusPlayer_WeaponRight;
    private readonly InputAction m_SamusPlayer_WeaponDown;
    private readonly InputAction m_SamusPlayer_WeaponLeft;
    private readonly InputAction m_SamusPlayer_Missiles;
    private readonly InputAction m_SamusPlayer_Morphball;
    /// <summary>
    /// Provides access to input actions defined in input action map "Samus Player".
    /// </summary>
    public struct SamusPlayerActions
    {
        private @PlayerInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public SamusPlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "SamusPlayer/Move".
        /// </summary>
        public InputAction @Move => m_Wrapper.m_SamusPlayer_Move;
        /// <summary>
        /// Provides access to the underlying input action "SamusPlayer/Look".
        /// </summary>
        public InputAction @Look => m_Wrapper.m_SamusPlayer_Look;
        /// <summary>
        /// Provides access to the underlying input action "SamusPlayer/Jump".
        /// </summary>
        public InputAction @Jump => m_Wrapper.m_SamusPlayer_Jump;
        /// <summary>
        /// Provides access to the underlying input action "SamusPlayer/Shoot".
        /// </summary>
        public InputAction @Shoot => m_Wrapper.m_SamusPlayer_Shoot;
        /// <summary>
        /// Provides access to the underlying input action "SamusPlayer/LockOn".
        /// </summary>
        public InputAction @LockOn => m_Wrapper.m_SamusPlayer_LockOn;
        /// <summary>
        /// Provides access to the underlying input action "SamusPlayer/WeaponUp".
        /// </summary>
        public InputAction @WeaponUp => m_Wrapper.m_SamusPlayer_WeaponUp;
        /// <summary>
        /// Provides access to the underlying input action "SamusPlayer/WeaponRight".
        /// </summary>
        public InputAction @WeaponRight => m_Wrapper.m_SamusPlayer_WeaponRight;
        /// <summary>
        /// Provides access to the underlying input action "SamusPlayer/WeaponDown".
        /// </summary>
        public InputAction @WeaponDown => m_Wrapper.m_SamusPlayer_WeaponDown;
        /// <summary>
        /// Provides access to the underlying input action "SamusPlayer/WeaponLeft".
        /// </summary>
        public InputAction @WeaponLeft => m_Wrapper.m_SamusPlayer_WeaponLeft;
        /// <summary>
        /// Provides access to the underlying input action "SamusPlayer/Missiles".
        /// </summary>
        public InputAction @Missiles => m_Wrapper.m_SamusPlayer_Missiles;
        /// <summary>
        /// Provides access to the underlying input action "SamusPlayer/Morphball".
        /// </summary>
        public InputAction @Morphball => m_Wrapper.m_SamusPlayer_Morphball;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_SamusPlayer; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="SamusPlayerActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(SamusPlayerActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="SamusPlayerActions" />
        public void AddCallbacks(ISamusPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_SamusPlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SamusPlayerActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Shoot.started += instance.OnShoot;
            @Shoot.performed += instance.OnShoot;
            @Shoot.canceled += instance.OnShoot;
            @LockOn.started += instance.OnLockOn;
            @LockOn.performed += instance.OnLockOn;
            @LockOn.canceled += instance.OnLockOn;
            @WeaponUp.started += instance.OnWeaponUp;
            @WeaponUp.performed += instance.OnWeaponUp;
            @WeaponUp.canceled += instance.OnWeaponUp;
            @WeaponRight.started += instance.OnWeaponRight;
            @WeaponRight.performed += instance.OnWeaponRight;
            @WeaponRight.canceled += instance.OnWeaponRight;
            @WeaponDown.started += instance.OnWeaponDown;
            @WeaponDown.performed += instance.OnWeaponDown;
            @WeaponDown.canceled += instance.OnWeaponDown;
            @WeaponLeft.started += instance.OnWeaponLeft;
            @WeaponLeft.performed += instance.OnWeaponLeft;
            @WeaponLeft.canceled += instance.OnWeaponLeft;
            @Missiles.started += instance.OnMissiles;
            @Missiles.performed += instance.OnMissiles;
            @Missiles.canceled += instance.OnMissiles;
            @Morphball.started += instance.OnMorphball;
            @Morphball.performed += instance.OnMorphball;
            @Morphball.canceled += instance.OnMorphball;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="SamusPlayerActions" />
        private void UnregisterCallbacks(ISamusPlayerActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Shoot.started -= instance.OnShoot;
            @Shoot.performed -= instance.OnShoot;
            @Shoot.canceled -= instance.OnShoot;
            @LockOn.started -= instance.OnLockOn;
            @LockOn.performed -= instance.OnLockOn;
            @LockOn.canceled -= instance.OnLockOn;
            @WeaponUp.started -= instance.OnWeaponUp;
            @WeaponUp.performed -= instance.OnWeaponUp;
            @WeaponUp.canceled -= instance.OnWeaponUp;
            @WeaponRight.started -= instance.OnWeaponRight;
            @WeaponRight.performed -= instance.OnWeaponRight;
            @WeaponRight.canceled -= instance.OnWeaponRight;
            @WeaponDown.started -= instance.OnWeaponDown;
            @WeaponDown.performed -= instance.OnWeaponDown;
            @WeaponDown.canceled -= instance.OnWeaponDown;
            @WeaponLeft.started -= instance.OnWeaponLeft;
            @WeaponLeft.performed -= instance.OnWeaponLeft;
            @WeaponLeft.canceled -= instance.OnWeaponLeft;
            @Missiles.started -= instance.OnMissiles;
            @Missiles.performed -= instance.OnMissiles;
            @Missiles.canceled -= instance.OnMissiles;
            @Morphball.started -= instance.OnMorphball;
            @Morphball.performed -= instance.OnMorphball;
            @Morphball.canceled -= instance.OnMorphball;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="SamusPlayerActions.UnregisterCallbacks(ISamusPlayerActions)" />.
        /// </summary>
        /// <seealso cref="SamusPlayerActions.UnregisterCallbacks(ISamusPlayerActions)" />
        public void RemoveCallbacks(ISamusPlayerActions instance)
        {
            if (m_Wrapper.m_SamusPlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="SamusPlayerActions.AddCallbacks(ISamusPlayerActions)" />
        /// <seealso cref="SamusPlayerActions.RemoveCallbacks(ISamusPlayerActions)" />
        /// <seealso cref="SamusPlayerActions.UnregisterCallbacks(ISamusPlayerActions)" />
        public void SetCallbacks(ISamusPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_SamusPlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SamusPlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="SamusPlayerActions" /> instance referencing this action map.
    /// </summary>
    public SamusPlayerActions @SamusPlayer => new SamusPlayerActions(this);

    // MorphBall
    private readonly InputActionMap m_MorphBall;
    private List<IMorphBallActions> m_MorphBallActionsCallbackInterfaces = new List<IMorphBallActions>();
    private readonly InputAction m_MorphBall_MorphBallMove;
    private readonly InputAction m_MorphBall_Bomb;
    private readonly InputAction m_MorphBall_PowerBomb;
    private readonly InputAction m_MorphBall_SpiderBall;
    private readonly InputAction m_MorphBall_SpringBall;
    private readonly InputAction m_MorphBall_ChangeSamus;
    /// <summary>
    /// Provides access to input actions defined in input action map "MorphBall".
    /// </summary>
    public struct MorphBallActions
    {
        private @PlayerInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public MorphBallActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "MorphBall/MorphBallMove".
        /// </summary>
        public InputAction @MorphBallMove => m_Wrapper.m_MorphBall_MorphBallMove;
        /// <summary>
        /// Provides access to the underlying input action "MorphBall/Bomb".
        /// </summary>
        public InputAction @Bomb => m_Wrapper.m_MorphBall_Bomb;
        /// <summary>
        /// Provides access to the underlying input action "MorphBall/PowerBomb".
        /// </summary>
        public InputAction @PowerBomb => m_Wrapper.m_MorphBall_PowerBomb;
        /// <summary>
        /// Provides access to the underlying input action "MorphBall/SpiderBall".
        /// </summary>
        public InputAction @SpiderBall => m_Wrapper.m_MorphBall_SpiderBall;
        /// <summary>
        /// Provides access to the underlying input action "MorphBall/SpringBall".
        /// </summary>
        public InputAction @SpringBall => m_Wrapper.m_MorphBall_SpringBall;
        /// <summary>
        /// Provides access to the underlying input action "MorphBall/ChangeSamus".
        /// </summary>
        public InputAction @ChangeSamus => m_Wrapper.m_MorphBall_ChangeSamus;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_MorphBall; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="MorphBallActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(MorphBallActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="MorphBallActions" />
        public void AddCallbacks(IMorphBallActions instance)
        {
            if (instance == null || m_Wrapper.m_MorphBallActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MorphBallActionsCallbackInterfaces.Add(instance);
            @MorphBallMove.started += instance.OnMorphBallMove;
            @MorphBallMove.performed += instance.OnMorphBallMove;
            @MorphBallMove.canceled += instance.OnMorphBallMove;
            @Bomb.started += instance.OnBomb;
            @Bomb.performed += instance.OnBomb;
            @Bomb.canceled += instance.OnBomb;
            @PowerBomb.started += instance.OnPowerBomb;
            @PowerBomb.performed += instance.OnPowerBomb;
            @PowerBomb.canceled += instance.OnPowerBomb;
            @SpiderBall.started += instance.OnSpiderBall;
            @SpiderBall.performed += instance.OnSpiderBall;
            @SpiderBall.canceled += instance.OnSpiderBall;
            @SpringBall.started += instance.OnSpringBall;
            @SpringBall.performed += instance.OnSpringBall;
            @SpringBall.canceled += instance.OnSpringBall;
            @ChangeSamus.started += instance.OnChangeSamus;
            @ChangeSamus.performed += instance.OnChangeSamus;
            @ChangeSamus.canceled += instance.OnChangeSamus;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="MorphBallActions" />
        private void UnregisterCallbacks(IMorphBallActions instance)
        {
            @MorphBallMove.started -= instance.OnMorphBallMove;
            @MorphBallMove.performed -= instance.OnMorphBallMove;
            @MorphBallMove.canceled -= instance.OnMorphBallMove;
            @Bomb.started -= instance.OnBomb;
            @Bomb.performed -= instance.OnBomb;
            @Bomb.canceled -= instance.OnBomb;
            @PowerBomb.started -= instance.OnPowerBomb;
            @PowerBomb.performed -= instance.OnPowerBomb;
            @PowerBomb.canceled -= instance.OnPowerBomb;
            @SpiderBall.started -= instance.OnSpiderBall;
            @SpiderBall.performed -= instance.OnSpiderBall;
            @SpiderBall.canceled -= instance.OnSpiderBall;
            @SpringBall.started -= instance.OnSpringBall;
            @SpringBall.performed -= instance.OnSpringBall;
            @SpringBall.canceled -= instance.OnSpringBall;
            @ChangeSamus.started -= instance.OnChangeSamus;
            @ChangeSamus.performed -= instance.OnChangeSamus;
            @ChangeSamus.canceled -= instance.OnChangeSamus;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="MorphBallActions.UnregisterCallbacks(IMorphBallActions)" />.
        /// </summary>
        /// <seealso cref="MorphBallActions.UnregisterCallbacks(IMorphBallActions)" />
        public void RemoveCallbacks(IMorphBallActions instance)
        {
            if (m_Wrapper.m_MorphBallActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="MorphBallActions.AddCallbacks(IMorphBallActions)" />
        /// <seealso cref="MorphBallActions.RemoveCallbacks(IMorphBallActions)" />
        /// <seealso cref="MorphBallActions.UnregisterCallbacks(IMorphBallActions)" />
        public void SetCallbacks(IMorphBallActions instance)
        {
            foreach (var item in m_Wrapper.m_MorphBallActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MorphBallActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="MorphBallActions" /> instance referencing this action map.
    /// </summary>
    public MorphBallActions @MorphBall => new MorphBallActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Samus Player" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="SamusPlayerActions.AddCallbacks(ISamusPlayerActions)" />
    /// <seealso cref="SamusPlayerActions.RemoveCallbacks(ISamusPlayerActions)" />
    public interface ISamusPlayerActions
    {
        /// <summary>
        /// Method invoked when associated input action "Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Look" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLook(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Jump" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnJump(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Shoot" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnShoot(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LockOn" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLockOn(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "WeaponUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnWeaponUp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "WeaponRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnWeaponRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "WeaponDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnWeaponDown(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "WeaponLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnWeaponLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Missiles" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMissiles(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Morphball" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMorphball(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "MorphBall" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="MorphBallActions.AddCallbacks(IMorphBallActions)" />
    /// <seealso cref="MorphBallActions.RemoveCallbacks(IMorphBallActions)" />
    public interface IMorphBallActions
    {
        /// <summary>
        /// Method invoked when associated input action "MorphBall Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMorphBallMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Bomb" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBomb(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Power Bomb" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPowerBomb(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SpiderBall" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpiderBall(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SpringBall" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpringBall(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Change Samus" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnChangeSamus(InputAction.CallbackContext context);
    }
}
